### ISSUE TITLE
Comment counts don't work if you're using Disqus

### ISSUE THREAD

**Issue by dvanderbeek** [FlyoverWorks/storytime#102]

**Comment by dvanderbeek** [comment]
Also, allowing you to change the post url style means you lose Disqus comments if you ever change URL style

**Comment by dvanderbeek** [comment]
We probably need to create a unique identifier for each post to use with Disqus. This will allow us to get the comment count and also use that to retrieve the comment thread instead of the URL since that may change.

**Comment by eanlain** [comment]
Seems like this may be closed... I noticed the following partial was added some time ago, and comment counts seem to be showing up accurately on FlyoverWorks.

```erb
<%= render "storytime/application/storytime/disqus_comment_counts" %>
```
