### ISSUE TITLE
Version 2.0 Upgrade/Migration Guide

### ISSUE THREAD

**Issue by cdesch** [FlyoverWorks/storytime#116]
Hi @flyoverworks,

I see you're planning on bumping storytime to `2.0`. Could you please include an upgrade guide/notes in the `README.MD` for those moving from version`1.2` to `2.0`?

**Comment by bcroesch** [comment]
@cdesch - We put together an upgrade guide that's available on the wiki: https://github.com/FlyoverWorks/storytime/wiki/Upgrading-from-Version-1.X.X-to-Version-2.0.0

We'll make sure to add it to the readme as well.

**Comment by cdesch** [comment]
@bcroesch Thanks! I didn't see that. Good stuff!

**Comment by bcroesch** [comment]
@cdesch also meant to mention, if you run into any issues while upgrading, feel free to reach out. Either on here or you can ping me on twitter (@bcroesch) -- happy to help. I'll be upgrading some of our client apps this weekend, so hopefully will find any kinks and we can release the official 2.0 next week.

**Comment by cdesch** [comment]
@bcroesch sounds great. Actually, if you have something you believe is stable, I would be more than willing to give a beta or RC a dry run this week and provide feedback.

**Comment by bcroesch** [comment]
@cdesch - just pushed a bunch of fixes & updates today. Would love it if you gave master a run through. 

We've updated about 4 production apps thus far and all seem to be working well, but if you run into any snags, just give me a shout and I'm happy to help.
