### ISSUE TITLE
Tag-based routes are broken

### ISSUE THREAD

**Issue by bcroesch** [FlyoverWorks/storytime#122]
We have a route for specific tags (e.g. /tags/tag-name), but they are currently broken after the switch to multiple blogs. The query-param tag filtering still works fine (e.g. /posts?tag=tag-name). 

Should we try to make the first style work in some capacity (perhaps /blog-slug/tag-name), or should we just leave it to the query-param style? If the latter, we should delete the broken route.

**Comment by eanlain** [comment]
I'd vote for the latter. Would the route for /tags/tag-name, especially since the route just takes you to posts#index...
