### ISSUE TITLE
Errors during storytime install

### ISSUE THREAD

**Issue by rusikf** [FlyoverWorks/storytime#125]
In particular, there is strange syntax error in migration ```db/migrate/20150412190334_add_title_and_content_index_to_storytime_post.storytime.rb`` if i choose postres on install.
I am also tryed storytime from git, but the error, is still appearing.
```ruby
$ storytime install
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Starting install of Storytime...
Setting up Storytime engine mount point...
Where would you like to mount Storytime within the host app? (/) 
      insert  config/routes.rb
Storytime mount point added to routes file

Setting up Storytime initializer file...
Name of the model that you want to use for Storytime users? (User) 
Do you want to enable certain models to be accessible to CRUD operations within the Storytime admin dashboard? [y/n] (n) 
Do you want to use /storytime as the location of the dashboard? [y/n] (y) 
Do you want to use additional post types other than Storytime::Page and Storytime::BlogPost? [y/n] (n) 
What should the character limit be for post titles? (100) 
What should the character limit be for post excerpts? (500) 
What database is being used to run this application? [mysql, postgres, sqlite3, other] postgres
Do you want to enable file uploads? [y/n] (y) 
What type of storage do you want to use for production environments? [:file, :s3] 
Your response must be one of: [:file, :s3]. Please try again.
What type of storage do you want to use for production environments? [:file, :s3] :file
      create  config/initializers/storytime.rb
Finished setting up Storytime initializer.

Devise initializer not found... trying to generate one.
No User model was found... creating one using Devise.
Adding `storytime_user` to User class...
      insert  app/models/user.rb
`storytime_user` added to User class.

Copying over Storytime migrations...
Finished copying Storytime migrations.

Would you like to migrate your database now? [y/n] (y) 
Running database migrations...
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: near "USING": syntax error: CREATE INDEX posts_title_contentx ON storytime_posts USING gin(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, '')));/home/rs/Work/story_time_app/db/migrate/20150412190334_add_title_and_content_index_to_storytime_post.storytime.rb:5:in `up'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: SQLite3::SQLException: near "USING": syntax error: CREATE INDEX posts_title_contentx ON storytime_posts USING gin(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, '')));
/home/rs/Work/story_time_app/db/migrate/20150412190334_add_title_and_content_index_to_storytime_post.storytime.rb:5:in `up'
-e:1:in `<main>'
SQLite3::SQLException: near "USING": syntax error
/home/rs/Work/story_time_app/db/migrate/20150412190334_add_title_and_content_index_to_storytime_post.storytime.rb:5:in `up'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Finished running database migrations.

Would you like to copy Storytime's views to your host app? [y/n] (y) 
Copying Storytime views...
Could not find "blog_posts" in any of your source paths. Your current source paths are: 
/home/rs/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime
Finished copying Storytime views.

Finished installing Storytime.
Start up your Rails server and navigate to http://localhost:3000/ to use Storytime.

```

**Comment by eanlain** [comment]
It seems like your database is SQLite3. Try opening the `config/initializers/storytime.rb` file and changing `config.search_adapter = Storytime::PostgresSearchAdapter` to `config.search_adapter = Storytime::Sqlite3SearchAdapter`. 

Let me know if that works for you.

**Comment by eanlain** [comment]
Once you change that you should just be able to run `rake db:migrate` to finish the process.

**Comment by rusikf** [comment]
I removed the previous app, and created new, during installing i selected sqlte3 and with it works with it.

**Comment by rusikf** [comment]
I think this issue must not be closed, because the problem is not resolved. You can now install storytime gem, select postres during installation and you will have this error

**Comment by eanlain** [comment]
By default a new Rails application `rails new some_new_app` will create Rails database using the SQLite3 database. You can create a Rails application using Postgres or MySQL by passing the `-d` parameter (i.e. `rails new some_new_app -d postgresql`).

The guided installs asks you which database your app is using - the new app that you created was using a SQLite3 database, not a Postgres one... The migration that returned the error uses a conditional based on that setting (the `config.search_adapter` setting in `config/initializers/storytime.rb`) to determine which database query should be run. If `config.search_adapter` is improperly set then the result upon trying to migrate your database would be the error that you ran into.

**Comment by rusikf** [comment]
@eanlain , thank's for great explanation :smile: 
What you think about new feature - ```storytime will show warning if developer choose another adapter( which he doesn't use in my case) ```?

**Comment by eanlain** [comment]
I don't think that's a high priority for Storytime at this moment.

In a way, the error is the warning that the developer chose the wrong adapter for their database. Fixing the error is as simple as opening the `config/initializers/storytime.rb` file, changing `config.search_adapter`, and re-running `rake db:migrate`.

**Comment by gugl** [comment]
I just created a new rails app with postgresql as the database. And on storytime install I selected postgres as the database adapter to use and still got that error:

Copying Storytime views...
Could not find "blog_posts" in any of your source paths. Your current source paths are:
/usr/local/Cellar/rbenv/0.4.0/versions/2.2.1/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime
Finished copying Storytime views.

Any suggestions? That's already in the storytime initializer: 

config.search_adapter = Storytime::PostgresSearchAdapter

**Comment by gugl** [comment]
Here is what I got on storytime install:

storytime install
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
      globalid (>= 0.3.0)
      mail (>= 2.5.4, ~> 2.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Starting install of Storytime...
Setting up Storytime engine mount point...
Where would you like to mount Storytime within the host app? (/)
      insert  config/routes.rb
Storytime mount point added to routes file

Setting up Storytime initializer file...
Name of the model that you want to use for Storytime users? (User)
Do you want to enable certain models to be accessible to CRUD operations within the Storytime admin dashboard? [y/n] (n)
Do you want to use /storytime as the location of the dashboard? [y/n] (y)
Do you want to use additional post types other than Storytime::Page and Storytime::BlogPost? [y/n] (n)
What should the character limit be for post titles? (100)
What should the character limit be for post excerpts? (500)
What database is being used to run this application? [mysql, postgres, sqlite3, other] postgres
Do you want to enable file uploads? [y/n] (y)
What type of storage do you want to use for production environments? [:file, :s3] :s3
What's the name of your S3 bucket? somebucket
   identical  config/initializers/storytime.rb
Finished setting up Storytime initializer.

Adding `storytime_user` to User class...
      insert  app/models/user.rb
`storytime_user` added to User class.

Copying over Storytime migrations...
Finished copying Storytime migrations.

Would you like to migrate your database now? [y/n] (y)
Running database migrations...
Finished running database migrations.

Would you like to copy Storytime's views to your host app? [y/n] (y)
Copying Storytime views...
Could not find "blog_posts" in any of your source paths. Your current source paths are:
/usr/local/Cellar/rbenv/0.4.0/versions/2.2.1/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime
Finished copying Storytime views.

Finished installing Storytime.
Start up your Rails server and navigate to http://localhost:3000/ to use Storytime.

**Comment by eanlain** [comment]
@gugl it looks like you're getting that error because there's no longer a "blog_posts" views folder in Storytime - it looks like it was renamed "blogs" but we forgot to remove "blog_posts" from the `copy_views` method in the view generator.

Everything should still work fine though with Storytime - not really a database issue.

Thanks for letting us know about your error though, I'll fix the error.

**Comment by gugl** [comment]
Hi. Yes. Thats what I found out as well. The BlogPost model is also mentioned in one of the installer questions. I just wanted to make a fork and fix that. Would be good to make a new minor release then as every installer user gets that error at the moment.

**Comment by wmuengineer** [comment]
Just ran into the same problem thanks for asking about this @gugl saved me loads of time.

**Comment by roseaboveit** [comment]
FYI, I updated the wiki for the views generation so that this issue will not be automatically an issue for folks copy-pasting those commands.

I was a bit unnerved by the fact that I could just make changes without a PR but such is the nature of wikis I guess. Hope I didn't step on anyone's toes.
