### ISSUE TITLE
`bundle binstub storytime` returns storytime has no executables

### ISSUE THREAD

**Issue by dimanyc** [FlyoverWorks/storytime#126]
I'm getting the following error message when trying  *bundle binstub storytime*:

    storytime has no executables, but you may want one from a gem it depends on.
      fog has: fog
      nokogiri has: nokogiri

I'm running: Rails 4.1.6, Ruby, ruby 2.0.0p451 on Win 8.1

**Comment by eanlain** [comment]
What version of Storytime are you using?

**Comment by dimanyc** [comment]
1.2.0

**Comment by eanlain** [comment]
The `bundle binstub storytime` command only works for Storytime v2.0.0+.

If you want to stick with v1.2.0 checkout the [README for that release](https://github.com/FlyoverWorks/storytime/blob/aa4e74208e07f5014e8b39ee1db16053171c69ae/README.md).

If you want the latest Storytime (v2.0.0), update your gemfile with `gem storytime, '~> 2.0.0'` and run `bundle` or by running `bundle update --source storytime`. After updating to v2.0.0 you should be able to continue with the guided install process that's currently in the [README](https://github.com/FlyoverWorks/storytime/blob/master/README.md) and [wiki](https://github.com/FlyoverWorks/storytime/wiki/Setup).

**Comment by dimanyc** [comment]
yep. Thanks!
