### ISSUE TITLE
Swap default-ness on draft vs. published tabs

### ISSUE THREAD

**Issue by bcroesch** [FlyoverWorks/storytime#129]
In most of our sites, we almost always have no draft posts, so the default view is blank. I think we should consider swapping this so that you see the published posts list by default

**Comment by dvanderbeek** [comment]
I agree. Do you think we should swap the order or add a new tab that shows "All" as the default and we can add a label to show the ones that are drafts. The new tabs would be: All, Drafts, Published

**Comment by bcroesch** [comment]
I like the "All" idea a lot. That'd be my vote

**Comment by eanlain** [comment]
I vote for the addition of an "All" tab as well.

**Comment by groe** [comment]
+1 for All

**Comment by rusikf** [comment]
:+1:  for All

**Comment by dvanderbeek** [comment]
This is added in dev and should be included in the next release.
