### ISSUE TITLE
Blog settings error

### ISSUE THREAD

**Issue by dvanderbeek** [FlyoverWorks/storytime#133]
When I run the dummy server and attempt to change the title of a blog from the blog settings menu, the response is a 422 error.

**Comment by dvanderbeek** [comment]
Looks like the error on the @blog record is that draft_content can't be blank. It looks like we have Blog inheriting from Page, which inherits from Post, which includes the has_versions concern. We probably need to switch up the way our models are set up to fix this.

**Comment by dvanderbeek** [comment]
Also, it appears this only happens for the default blog that gets created when you create a site. In the dashboard/blogs_controller there's a pretty dirty hack that just sets :draft_content to "test" on any other Blogs that get created, along with a few other attributes that really don't belong on a Blog record. I guess the easiest fix for now would be to do something similar for the default Blog.

**Comment by eanlain** [comment]
@dvanderbeek is this still an issue? I can't seem to reproduce...

**Comment by dvanderbeek** [comment]
Hmm, looks like it's working on the dummy app now. I'll close the issue and we can re-open it if we run into it again.
