### ISSUE TITLE
Heroku deploy sample app has issue

### ISSUE THREAD

**Issue by ThomasBush** [FlyoverWorks/storytime#134]
My attempted Heroku deploy of the sample app failed with the following issue
```
Configure environment
   There was an issue setting up your app environment.
   could not find the source blob
```
I will try to pull down and run locally, just figured I would give you a heads up.  I am excited to try Storytime!

**Comment by eanlain** [comment]
Hmm, it seemed to work when I deployed using the deploy to Heroku button in the README. May try again? It was probably an issue with pulling down one of the gems from RubyGems.

**Comment by ThomasBush** [comment]
@eanlain Sorry for delayed response, I tried again and everything worked as expected.

**Comment by eanlain** [comment]
No worries, glad to hear that it worked.
