### ISSUE TITLE
No such file or directory - bin/spring

### ISSUE THREAD

**Issue by Zhomart** [FlyoverWorks/storytime#139]
I just created Rails 4.2.1 project, added `gem 'storytime'` to Gemfile. After `$ bundle install` I did `$ bundle binstub storytime` and then `$ storytime install` and got error:

```
$ storytime install
/Users/zhomart/.rvm/gems/ruby-2.2.1/gems/storytime-2.0.0/lib/storytime/cli/install.rb:60:in ``': No such file or directory - bin/spring (Errno::ENOENT)
	from /Users/zhomart/.rvm/gems/ruby-2.2.1/gems/storytime-2.0.0/lib/storytime/cli/install.rb:60:in `interactive'
```

`Gemfile` doesn't contain gem spring. Is it necessary to add it?

**Comment by fatbelfegor** [comment]
At first you need to generate new rails app.

**Comment by eanlain** [comment]
Yeah, there's two points in the installer where we try to stop spring, by running `bin/spring stop`, but we should probably handle that differently....

Quick fix for the moment:

```ruby
group :development do
  gem 'spring'
end
```

**Comment by eanlain** [comment]
Spring, by default, is included in the Gemfile for any app generated using Rails 4.1+ and the `rails new` command.

**Comment by Zhomart** [comment]
Thank you for the answer. It works. 

Btw, `spring` is not included in Gemfile by rails `4.2.1`. Just tested.

**Comment by eanlain** [comment]
Ah, good to know - thanks for checking.

**Comment by chrise86** [comment]
I had the same problem, added spring to gem file (development group) and still getting the same problem...
