### ISSUE TITLE
ArgumentError in Storytime::Dashboard::Pages#index

### ISSUE THREAD

**Issue by cdesch** [FlyoverWorks/storytime#150]
I get this error when creating after creating a new storytime and trying to go to the dashboard for the first time:

     Started GET "/p/storytime" for 127.0.0.1 at 2015-04-25 18:19:24 -0400
    Processing by Storytime::Dashboard::PagesController#index as HTML
       (0.1ms)  SELECT COUNT(*) FROM "storytime_sites"
      Storytime::Site Load (0.1ms)  SELECT  "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."custom_domain" = ? LIMIT 1  [["custom_domain", "localhost"]]
      User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
      CACHE (0.0ms)  SELECT COUNT(*) FROM "storytime_sites"
       (0.1ms)  SELECT COUNT(*) FROM "storytime_memberships" WHERE "storytime_memberships"."site_id" = ? AND "storytime_memberships"."user_id" = ?  [["site_id", 1], ["user_id", 1]]
      Storytime::Action Load (0.1ms)  SELECT  "storytime_actions".* FROM "storytime_actions" WHERE "storytime_actions"."guid" = ? LIMIT 1  [["guid", "d8a1b1"]]
      Storytime::Site Load (0.1ms)  SELECT  "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."id" = ? LIMIT 1  [["id", 1]]
      Storytime::Membership Load (0.1ms)  SELECT  "storytime_memberships".* FROM "storytime_memberships" WHERE "storytime_memberships"."site_id" = ? AND "storytime_memberships"."user_id" = ? AND "storytime_memberships"."site_id" = 1 LIMIT 1  [["site_id", 1], ["user_id", 1]]
      Storytime::Role Load (0.1ms)  SELECT  "storytime_roles".* FROM "storytime_roles" WHERE "storytime_roles"."id" = ? LIMIT 1  [["id", 3]]
      Storytime::Action Exists (0.3ms)  SELECT "storytime_actions".* FROM "storytime_actions" INNER JOIN "storytime_permissions" ON "storytime_actions"."id" = "storytime_permissions"."action_id" WHERE "storytime_permissions"."site_id" = ? AND "storytime_permissions"."role_id" = ? AND "storytime_actions"."id" = ?  [["site_id", 1], ["role_id", 3], ["id", 1]]
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime/dashboard/pages/_new_button.html.erb (1.1ms)
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime/dashboard/pages/_index_title.html.erb (0.8ms)
      Storytime::Post Load (0.3ms)  SELECT  "storytime_posts".* FROM "storytime_posts" WHERE "storytime_posts"."site_id" = ? AND "storytime_posts"."type" = ? AND (published_at IS NULL OR published_at > '2015-04-25 22:19:24.881416')  ORDER BY "storytime_posts"."updated_at" DESC LIMIT 10 OFFSET 0  [["site_id", 1], ["type", "Storytime::Page"]]
       (0.1ms)  SELECT COUNT(*) FROM "storytime_posts" WHERE "storytime_posts"."site_id" = ? AND "storytime_posts"."type" = ? AND (published_at IS NULL OR published_at > '2015-04-25 22:19:24.881416')  [["site_id", 1], ["type", "Storytime::Page"]]
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime/dashboard/posts/_list.html.erb (103.4ms)
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime/dashboard/posts/index.html.erb within layouts/storytime/dashboard (826.3ms)
      CACHE (0.0ms)  SELECT  "storytime_memberships".* FROM "storytime_memberships" WHERE "storytime_memberships"."site_id" = ? AND "storytime_memberships"."user_id" = ? AND "storytime_memberships"."site_id" = 1 LIMIT 1  [["site_id", 1], ["user_id", 1]]
      Storytime::Action Load (0.2ms)  SELECT  "storytime_actions".* FROM "storytime_actions" WHERE "storytime_actions"."guid" = ? LIMIT 1  [["guid", "1f7d47"]]
      CACHE (0.0ms)  SELECT  "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."id" = ? LIMIT 1  [["id", 1]]
      CACHE (0.0ms)  SELECT  "storytime_memberships".* FROM "storytime_memberships" WHERE "storytime_memberships"."site_id" = ? AND "storytime_memberships"."user_id" = ? AND "storytime_memberships"."site_id" = 1 LIMIT 1  [["site_id", 1], ["user_id", 1]]
      CACHE (0.0ms)  SELECT  "storytime_roles".* FROM "storytime_roles" WHERE "storytime_roles"."id" = ? LIMIT 1  [["id", 3]]
      Storytime::Action Exists (0.1ms)  SELECT "storytime_actions".* FROM "storytime_actions" INNER JOIN "storytime_permissions" ON "storytime_actions"."id" = "storytime_permissions"."action_id" WHERE "storytime_permissions"."site_id" = ? AND "storytime_permissions"."role_id" = ? AND "storytime_actions"."id" = ?  [["site_id", 1], ["role_id", 3], ["id", 4]]
      Storytime::Action Load (0.1ms)  SELECT  "storytime_actions".* FROM "storytime_actions" WHERE "storytime_actions"."guid" = ? LIMIT 1  [["guid", "47342a"]]
      CACHE (0.0ms)  SELECT  "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."id" = ? LIMIT 1  [["id", 1]]
      CACHE (0.0ms)  SELECT  "storytime_memberships".* FROM "storytime_memberships" WHERE "storytime_memberships"."site_id" = ? AND "storytime_memberships"."user_id" = ? AND "storytime_memberships"."site_id" = 1 LIMIT 1  [["site_id", 1], ["user_id", 1]]
      CACHE (0.0ms)  SELECT  "storytime_roles".* FROM "storytime_roles" WHERE "storytime_roles"."id" = ? LIMIT 1  [["id", 3]]
      Storytime::Action Exists (0.1ms)  SELECT "storytime_actions".* FROM "storytime_actions" INNER JOIN "storytime_permissions" ON "storytime_actions"."id" = "storytime_permissions"."action_id" WHERE "storytime_permissions"."site_id" = ? AND "storytime_permissions"."role_id" = ? AND "storytime_actions"."id" = ?  [["site_id", 1], ["role_id", 3], ["id", 3]]
      Storytime::Action Load (0.1ms)  SELECT  "storytime_actions".* FROM "storytime_actions" WHERE "storytime_actions"."guid" = ? LIMIT 1  [["guid", "d29d76"]]
      CACHE (0.0ms)  SELECT  "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."id" = ? LIMIT 1  [["id", 1]]
      CACHE (0.0ms)  SELECT  "storytime_memberships".* FROM "storytime_memberships" WHERE "storytime_memberships"."site_id" = ? AND "storytime_memberships"."user_id" = ? AND "storytime_memberships"."site_id" = 1 LIMIT 1  [["site_id", 1], ["user_id", 1]]
      CACHE (0.0ms)  SELECT  "storytime_roles".* FROM "storytime_roles" WHERE "storytime_roles"."id" = ? LIMIT 1  [["id", 3]]
      Storytime::Action Exists (0.1ms)  SELECT "storytime_actions".* FROM "storytime_actions" INNER JOIN "storytime_permissions" ON "storytime_actions"."id" = "storytime_permissions"."action_id" WHERE "storytime_permissions"."site_id" = ? AND "storytime_permissions"."role_id" = ? AND "storytime_actions"."id" = ?  [["site_id", 1], ["role_id", 3], ["id", 6]]
      Storytime::Membership Load (0.2ms)  SELECT "storytime_memberships".* FROM "storytime_memberships" WHERE "storytime_memberships"."user_id" = 1 AND ("storytime_memberships"."site_id" IS NOT NULL)
      Storytime::Site Load (0.1ms)  SELECT "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."id" IN (1)
      CACHE (0.0ms)  SELECT  "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."custom_domain" = ? LIMIT 1  [["custom_domain", "localhost"]]
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime/dashboard/_navigation.html.erb (209.9ms)
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/storytime-2.0.0/app/views/storytime/application/storytime/_navigation.html.erb (365.0ms)
    Completed 500 Internal Server Error in 2449ms
    ** [Airbrake] Notice was not sent due to configuration:         
      Environment Monitored? false         
      API key set? true

    ActionView::Template::Error (wrong number of arguments (2 for 1)):
        58:     <ul class="nav nav-menu-nav">
        59:       <% Storytime::Membership.all_for_user(current_user).each do |membership| %>
        60:         <% if membership.site == current_storytime_site %>
        61:           <li class="active"><%= link_to icon("check", membership.site.title), "", class: "storytime-menu-toggle" %></li>
        62:         <% else %>
        63:           <li><%= link_to membership.site.title, storytime.dashboard_url(host: membership.site.custom_domain) %></li>
        64:         <% end %>
      /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/spree-fe3327f9bc3b/backend/app/helpers/spree/admin/navigation_helper.rb:155:in `icon'
      storytime (2.0.0) app/views/storytime/dashboard/_navigation.html.erb:61:in `block in _2946e45011707faaaf191639a083ee0c'
      activerecord (4.2.0) lib/active_record/relation/delegation.rb:46:in `each'
      activerecord (4.2.0) lib/active_record/relation/delegation.rb:46:in `each'
      storytime (2.0.0) app/views/storytime/dashboard/_navigation.html.erb:59:in `_2946e45011707faaaf191639a083ee0c'
      actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:143:in `render'
      deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
      actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:309:in `render'
      actionview (4.2.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
      actionview (4.2.0) lib/action_view/helpers/rendering_helper.rb:35:in `render'
      haml (4.0.6) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
      storytime (2.0.0) app/views/storytime/application/storytime/_navigation.html.erb:6:in `_440bd0a7f18b3a5ea4b3baa64c84bc7a'
      actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:143:in `render'
      deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
      actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:309:in `render'
      actionview (4.2.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
      actionview (4.2.0) lib/action_view/helpers/rendering_helper.rb:35:in `render'
      haml (4.0.6) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
      storytime (2.0.0) app/views/layouts/storytime/dashboard.html.erb:32:in `_95067decdc49339ecbcee32d6b00dcb0'
      actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:143:in `render'
      deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
      actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
      actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
      actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
      actionview (4.2.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
      actionview (4.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
      actionview (4.2.0) lib/action_view/rendering.rb:100:in `_render_template'
      actionpack (4.2.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
      actionview (4.2.0) lib/action_view/rendering.rb:83:in `render_to_body'
      actionpack (4.2.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
      actionpack (4.2.0) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
      actionpack (4.2.0) lib/abstract_controller/rendering.rb:25:in `render'
      actionpack (4.2.0) lib/action_controller/metal/rendering.rb:16:in `render'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
      activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
      /Users/cj/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
      activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
      activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
      actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
      actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
      actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
      actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
      activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
      activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:308:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:308:in `block (2 levels) in halting'
      storytime (2.0.0) app/controllers/storytime/application_controller.rb:65:in `scope_current_site'
      activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
      activesupport (4.2.0) lib/active_support/callbacks.rb:307:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:307:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
      activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
      actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
      actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
      actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
      actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
      actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
      railties (4.2.0) lib/rails/engine.rb:518:in `call'
      railties (4.2.0) lib/rails/railtie.rb:194:in `public_send'
      railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
      actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
      warden (1.2.3) lib/warden/manager.rb:34:in `catch'
      warden (1.2.3) lib/warden/manager.rb:34:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/etag.rb:24:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/head.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/runtime.rb:18:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/lock.rb:17:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
      airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.0) lib/rails/engine.rb:518:in `call'
      railties (4.2.0) lib/rails/application.rb:164:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/content_length.rb:15:in `call'
      thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
      thin (1.6.3) lib/thin/connection.rb:84:in `catch'
      thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
      thin (1.6.3) lib/thin/connection.rb:53:in `process'
      thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
      eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
      eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
      thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
      thin (1.6.3) lib/thin/server.rb:162:in `start'
      rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
      rack (1.6.0) lib/rack/server.rb:286:in `start'
      railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
      railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
      railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `tap'
      railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
      railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
      bin/rails:4:in `require'
      bin/rails:4:in `<top (required)>'
      -e:1:in `load'
      -e:1:in `<main>'

      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_source.erb (8.4ms)
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.html.erb (3.1ms)
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_request_and_response.html.erb (1.0ms)
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_web_console.html.erb (1.0ms)
      Rendered /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/template_error.html.erb within rescues/layout (838.9ms)

![screen shot 2015-04-25 at 6 19 47 pm](https://cloud.githubusercontent.com/assets/1207795/7335153/529d5ef2-eb79-11e4-8cbf-4ba236367330.png)

**Comment by dvanderbeek** [comment]
It looks like a gem you're using (something from Spree) is defining a helper method `icon()`. We use font-awesome, which also defines that helper method and it accepts arguments for the icon, text that gets printed next to the icon, and html_options.

**Comment by cdesch** [comment]
hmmm... i need to get these gems to play nice. I opened up [issue 6330 ](https://github.com/spree/spree/issues/6330) with spree. Is there anyway I can scope this helper method to the gem?

**Comment by dvanderbeek** [comment]
It’s really a conflict between spree and font-awesome-sass. I’m not sure how you’d fix this easily, other than getting spree to re-define the icon method or overwriting all the views in Storytime that call that method and manually printing out the markup for the font-awesome icons.


—

**Comment by cdesch** [comment]
disabling spree lets me work around this issue. Storytime also seems to have problems depending on which order you put the engine mount in the gem file.
