### ISSUE TITLE
Tag 'index' action error when selecting a tag from a blog post

### ISSUE THREAD

**Issue by cdesch** [FlyoverWorks/storytime#153]
I get the error `The action 'index' could not be found for Storytime::PostsController` when clicking the link `testtag` in the screenshot and going to the URL `localhost:3000/blog/tags/testtag` (screenshot at bottom with the tag in the blog post). The link should list all of the blog posts which have that tag.

Storytime is mounted at `mount Storytime::Engine => '/blog'`

I'm able to replicate the issue in this fresh install of storytime https://github.com/cdesch/story_test

    Started GET "/blog/tags/testtag" for 127.0.0.1 at 2015-04-29 09:18:49 -0400

    AbstractController::ActionNotFound (The action 'index' could not be found for Storytime::PostsController):
      actionpack (4.2.1) lib/abstract_controller/base.rb:132:in `process'
      actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
      actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
      actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
      actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
      actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
      actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
      actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
      actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
      actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
      railties (4.2.1) lib/rails/engine.rb:518:in `call'
      railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
      railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
      actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
      actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
      actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
      warden (1.2.3) lib/warden/manager.rb:34:in `catch'
      warden (1.2.3) lib/warden/manager.rb:34:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/etag.rb:24:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/head.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
      activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
      activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
      activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/runtime.rb:18:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/lock.rb:17:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
      airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.1) lib/rails/engine.rb:518:in `call'
      railties (4.2.1) lib/rails/application.rb:164:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/content_length.rb:15:in `call'
      thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
      thin (1.6.3) lib/thin/connection.rb:84:in `catch'
      thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
      thin (1.6.3) lib/thin/connection.rb:53:in `process'
      thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
      eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
      eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
      thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
      thin (1.6.3) lib/thin/server.rb:162:in `start'
      rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
      rack (1.6.0) lib/rack/server.rb:286:in `start'
      railties (4.2.1) lib/rails/commands/server.rb:80:in `start'
      railties (4.2.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
      railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
      railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `server'
      railties (4.2.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      railties (4.2.1) lib/rails/commands.rb:17:in `<top (required)>'
      bin/rails:4:in `require'
      bin/rails:4:in `<top (required)>'
      ruby-debug-ide (0.4.28) lib/ruby-debug-ide.rb:86:in `debug_load'
      ruby-debug-ide (0.4.28) lib/ruby-debug-ide.rb:86:in `debug_program'
      ruby-debug-ide (0.4.28) bin/rdebug-ide:121:in `<top (required)>'
      -e:1:in `load'
      -e:1:in `<main>'

![screen shot 2015-04-29 at 9 22 29 am](https://cloud.githubusercontent.com/assets/1207795/7391905/2e8603da-ee52-11e4-8534-f797a6e7822d.png)
)

**Comment by dvanderbeek** [comment]
Looks like this is related to #122. @eanlain Looks like you deleted the route for tags, but the links still point to storytime.tags_path. Don't we need to define that route, probably nested under the routes for blogs?

**Comment by cdesch** [comment]
Looks like you're also missing the rspec tests for the tags feature. I started writing them although when running the current rspec tests I am hitting a PG connection error (below). How are you configuring storytime to test with PG for rspec?

cjs-MBP15:storytime cj$ rspec
    DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

    You can opt into the new behavior and remove this warning by setting:

      config.active_record.raise_in_transactional_callbacks = true

     (called from <class:Media> at /Users/cj/rubyworkspace/storytime/app/models/storytime/media.rb:8)
    DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

    You can opt into the new behavior and remove this warning by setting:

      config.active_record.raise_in_transactional_callbacks = true

     (called from <class:Media> at /Users/cj/rubyworkspace/storytime/app/models/storytime/media.rb:8)
    /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect': FATAL:  database "storytime_dummy_test" does not exist (ActiveRecord::NoDatabaseError)
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:854:in `needs_migration?'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:397:in `load_schema_if_pending!'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:412:in `block in maintain_test_schema!'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:640:in `suppress_messages'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:417:in `method_missing'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:412:in `maintain_test_schema!'
      from /Users/cj/rubyworkspace/storytime/spec/spec_helper.rb:16:in `<top (required)>'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      from /Users/cj/rubyworkspace/storytime/spec/controllers/dashboard_controller_spec.rb:1:in `<top (required)>'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
      from /Users/cj/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'

**Comment by bcroesch** [comment]
Looks like the dummy app's db doesn't exist. From your storytime dir, try:
```
bundle exec rake app:db:create app:db:schema:load
```

Also just wanted to say thanks for all the testing & feedback. We have this running in several apps at this point, but you're definitely helping us clear issues in setups different from ours!

**Comment by eanlain** [comment]
We removed the `get 'tags/:tag', to: 'posts#index', as: :tag` route in #127, but it does look like I missed the instances of `tag_path` being used... I'll look into fixing them.

**Comment by bcroesch** [comment]
Closing since I believe this is fixed in master.

**Comment by cdesch** [comment]
This issue seems to persist after updating to the master branch


    Started GET "/blog/tags/anothertag" for 127.0.0.1 at 2015-05-15 13:11:03 -0400

    AbstractController::ActionNotFound (The action 'index' could not be found for  Storytime::PostsController):
    actionpack (4.2.1) lib/abstract_controller/base.rb:132:in `process'
    actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
    actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
    actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
    actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
    railties (4.2.1) lib/rails/engine.rb:518:in `call'
    railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
    railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
    actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
    warden (1.2.3) lib/warden/manager.rb:34:in `catch'
    warden (1.2.3) lib/warden/manager.rb:34:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/etag.rb:24:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/head.rb:13:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
    rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
    activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
    activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
    actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
    web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
    railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
    activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
    activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
    activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
    railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/runtime.rb:18:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/lock.rb:17:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
    airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    railties (4.2.1) lib/rails/engine.rb:518:in `call'
    railties (4.2.1) lib/rails/application.rb:164:in `call'
    newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
    rack (1.6.1) lib/rack/content_length.rb:15:in `call'
    thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
    thin (1.6.3) lib/thin/connection.rb:84:in `catch'
    thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
    thin (1.6.3) lib/thin/connection.rb:53:in `process'
    thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
    eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
    eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
    thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
    thin (1.6.3) lib/thin/server.rb:162:in `start'
    rack (1.6.1) lib/rack/handler/thin.rb:19:in `run'
    rack (1.6.1) lib/rack/server.rb:286:in `start'
    railties (4.2.1) lib/rails/commands/server.rb:80:in `start'
    railties (4.2.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
    railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
    railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `server'
    railties (4.2.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    railties (4.2.1) lib/rails/commands.rb:17:in `<top (required)>'
    bin/rails:4:in `require'
    bin/rails:4:in `<top (required)>'
    -e:1:in `load'
    -e:1:in `<main>'


![screen shot 2015-05-15 at 1 12 30 pm](https://cloud.githubusercontent.com/assets/1207795/7657940/198b65f6-fb04-11e4-9020-094958b8b861.png)
