### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by danielmag** [FlyoverWorks/storytime#160]
In the [wiki section](https://github.com/FlyoverWorks/storytime/wiki/Using-Custom-Post-Types#custom-fields) about custom fields you say we can have custom fields by adding them to the VideoPost. I tried this but it did not work, because I think storytime only uses it's post table and not the host's VideoPost table.

Do I need to add the columns to the storytime post table?

Thank you!

**Comment by dvanderbeek** [comment]
Yep, you need to add the fields to the storytime posts table because your custom VideoPost model should inherit from Storytime::BlogPost and they will share the same table in the database.

**Comment by danielmag** [comment]
In the wiki it seemed like it was meant to be added to my model.

Thank you!

**Comment by dvanderbeek** [comment]
No problem. I just updated the wiki to clarify this a bit.
