### ISSUE TITLE
Excerpt strip_tags

### ISSUE THREAD

**Issue by danielmag** [FlyoverWorks/storytime#161]
Sometimes when I create a new post I see that, in the excerpt things like quotes (") are changed to `&quot;`. After some investigation I saw that this was due to strip_tags being called on the excerpt.

Is this the expected behaviour?

Thank you!

**Comment by bcroesch** [comment]
Not sure I entirely follow -- those both look the same to me? Or am I missing something there?

Strip tags is just trying to sanitize our content some since we sometimes get garbage in the post content (e.g. someone pastes something from word).

**Comment by danielmag** [comment]
Sorry, github corrected the quote... I meant to say that thing like quotes are changed to `&quot;`

After some search i found that it is related to this bug in rails: https://github.com/rails/rails-html-sanitizer/issues/31

Seems like it was already fixed: https://github.com/rails/rails-html-sanitizer/pull/35
Will make it to rails 4.2.2

**Comment by optimum-dulopin** [comment]
i use rails 4.2.5.1 and there is still this bug
