### ISSUE TITLE
Broken post pagination

### ISSUE THREAD

**Issue by danielmag** [FlyoverWorks/storytime#162]
The pagination of posts is not working in the blog.
After some inspection I found that in the view, the param name is `:page_number` and the controller expects a param named `:page`.
This can be easily fixed in the view, but since every other controller I saw expected a `:page_number`, maybe you would like to change the controller.

Alternatively, you can just use the default for kaminari, which is `:page`. That way may be less error prone.

Thank you!

**Comment by eanlain** [comment]
Fix is currently in the `dev` branch, I'll close the issue when we push it to `master`. 

Thanks for letting us know!
