### ISSUE TITLE
The 2.0.0 gem is 3.01 MB vs 266 KB with 1.2.0 

### ISSUE THREAD

**Issue by andyattebery** [FlyoverWorks/storytime#166]

**Comment by eanlain** [comment]
It appears the culprit of v2.0.0 is the `screenshots` directory which houses over 3 MB of images. Just pushed a change which prevents that `screenshots` directory from being added into the gem...

Running `gem build storytime.gemspec` after that results in a compiled gem size of ~540 KB.
