### ISSUE TITLE
Post partial should display published_at instead of created_at

### ISSUE THREAD

**Issue by dvanderbeek** [FlyoverWorks/storytime#176]

**Comment by rusikf** [comment]
"Post Partial" - what do you mean? partial on Blog Post list?

**Comment by dvanderbeek** [comment]
https://github.com/FlyoverWorks/storytime/blob/master/app/views/storytime/posts/_post.html.erb

**Comment by rusikf** [comment]
It is not obvious for me, this partial doesn't belong to blog or pages ( I tried to create and view one page and one blog post but this partial is not rendered)
I can't find how to test this partial. Thank's for response.

**Comment by dvanderbeek** [comment]
I think this gets rendered on the show view for a blog (when listing the posts). I can look into this at some point, it's not a huge deal.
