### ISSUE TITLE
Turn entire list item into a link on the dashboard

### ISSUE THREAD

**Issue by dvanderbeek** [FlyoverWorks/storytime#60]
On the dashboard lists for Blog Posts, Pages, and Text Snippets, only the text is clickable. For easier navigation, the whole item should be a link. 

We might also want to consider removing the delete button since we also have it in the edit page and it might improve usability since you'd be able to click anywhere in the list without worrying about hitting delete. 

The view code for Snippets and Posts is also very similar. This should be refactored when making these changes to reduce duplication.

**Comment by bcroesch** [comment]
Believe this is also on 2.0 roadmap.
