### ISSUE TITLE
Indicate when a user is already signed in

### ISSUE THREAD

**Issue by dvanderbeek** [FlyoverWorks/storytime#61]
There is currently no way to tell if you're signed in when viewing a Storytime site. Perhaps we should have a link to the dashboard somewhere. Maybe floating in the lower right?

**Comment by bcroesch** [comment]
Going to close this since it's in trello as part of the 2.0 roadmap

**Comment by robertwbradford** [comment]
@bcroesch I'm not seeing a link to a roadmap anywhere. Is that publicly available?

**Comment by bcroesch** [comment]
@robertwbradford we have a trello board that we use internally. Let me double check it to make sure there is nothing client-related in there. Once that's the case, we can probably open it up.

**Comment by robertwbradford** [comment]
That would be great! Thanks.
