### ISSUE TITLE
Media inserts don't work properly

### ISSUE THREAD

**Issue by dvanderbeek** [FlyoverWorks/storytime#64]
I have storytime mounted at "/" with the blog as the homepage and `config.home_page_path = "/blog"`

When i try to insert media into a post, it adds `base_url/blo/uploads/....` instead of `base_url/uploads/....`

Looks like the issue is this helper method:

```
def full_media_file_url(media, size = nil)
        if media.file_url.starts_with?("http")
          media.file_url(size)
        else
          storytime_root_post_url[0..-2]+media.file_url(size)
        end
      end
```

**Comment by eanlain** [comment]
Yeah, that should be a -1 instead of -2...

**Comment by eanlain** [comment]
Carrierwave is just dumping uploads into /uploads as opposed to /blog/uploads, so that whole storytime_root_post_url is not needed. We could just get rid of the whole conditional and replace it with just `media.file_url(size)`.
