### ISSUE TITLE
preview blog post doesn't work

### ISSUE THREAD

**Issue by jessprice** [FlyoverWorks/storytime#65]
When I try to preview a blog post it comes up with an error saying something went wrong

**Comment by bcroesch** [comment]
I keep seeing this in our prod site as well. We've looked at it in the past and didn't come up with anything, but it's definitely a recurring problem. @eanlain would you mind taking a look at this today? If you can't recreate locally, try pulling a db backup off of the flyover prod site and restoring locally.

**Comment by eanlain** [comment]
Should work now in Storytime v1.0.7
