### ISSUE TITLE
RFE: Allow AWS keys to be put in secrets.yml

### ISSUE THREAD

**Issue by cdesch** [FlyoverWorks/storytime#93]
Please consider this RFE to allow the AWS keys to be stored in the `secrets.yml` as an alternative to using the environment variables  `STORYTIME_AWS_ACCESS_KEY_ID` and `STORYTIME_AWS_SECRET_KEY`.

This way they can be included with the rest of the environment variable

e.g. `config/secrets.yml`

    production:
      secret_key_base: 'secret_key'
      aws_access_key_id: 'another_secret'
      aws_secret_access_key: 'another_secret'

or 

    production:
      secret_key_base: ENV['MY_KEY_BASE']
      aws_access_key_id:  ENV['STORYTIME_AWS_ACCESS_KEY_ID']
      aws_secret_access_key: ENV['STORYTIME_AWS_SECRET_KEY']

and be used in `lib/storytime/engine.rb` 

          config.fog_credentials = {
            :provider               => 'AWS',
            :aws_access_key_id      => Rails.application.secrets.aws_access_key_id,
            :aws_secret_access_key  => Rails.application.secrets.aws_secret_access_key
          }

**Comment by bcroesch** [comment]
I think this sounds perfectly reasonable. One caveat being that we still support rails 4.0 and I believe secrets was added in 4.1, so we'd need to work around that. Not a huge deal though. We'll add it to the docket.

**Comment by eanlain** [comment]
Merged into dev branch.
