### ISSUE TITLE
ST - V2 - Links at top do not bring you back to the top of the page

### ISSUE THREAD

**Issue by jessprice** [FlyoverWorks/storytime#99]
If I am scrolled down into my post and I click either the image icon or the save/publish button on the top nav it does not scroll me to the top of the page to see the options for either link. It scrolls me about half way up.

**Comment by dvanderbeek** [comment]
56bd19fd26b526d827f7851e270ec90b5e8ed857 fixes this in multi-site branch.

**Comment by dvanderbeek** [comment]
also fixed in dev
